version: '3'
services:
  # haproxy:
  #   image: dockercloud/haproxy
  #   links:
  #     - www.jakelow.com
  #     #- fandf.jakelow.com
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

  www.jakelow.com:
    build: .
    environment:
      - VIRTUAL_HOST=http://www.jakelow.com, https://www.jakelow.com
    ports:
      - 80:80
      - 443:443
